### ISSUE TITLE
2 files missing in mainapp folder 

### ISSUE THREAD

**Issue by K3r0ui** [souslesens/souslesensVocables#256]
To access the ConfigEditor page in the Souslesens app, the mainapp.js and kg_upload_app.js files are necessary. However, these files are unavailable in the version that has been pushed on GitHub.

**Comment by K3r0ui** [comment]
i'll open pull request to fix this.

**Comment by xgaia** [comment]
Hello, this file are builded from sources present in mainapp dir. To build this files, run `npm run build` into the `mainapp` directory.

**Comment by K3r0ui** [comment]
Alright. Its working. 
then the doc should be updated in Readme file

# Install the server
npm ci
# Install the front
cd mainapp
npm ci
npm run build
# Go back to root
cd ..
should i update it ?
