### ISSUE TITLE
SQL sources management

### ISSUE THREAD

**Issue by claudefauconnet** [souslesens/souslesensVocables#563]
- [x] Ajouter un onglet `databases` dans le configEditor pour gérer les bases de données.

Les bases de données seront écrites dans un fichier `config/databases.json`

```json
[
  {
    "id": "toto",
    "driver":  "postgres",
    "host": "localhost",
    "port": 5432,
    "database": "tutu",
    "user": "toto",
    "password": "titi"  
  }
]
```

- [x] faire un script de migration pour créer le fichier `databases.json`

la migration devrai bouger l'entrée `SQLserver` dans le fichier `databases.json`

- [x] Modifier l'outil `kg-upload-app` pour qu'il utilise cette nouvelle configuration

- [x] documenter avec
    - [x] `config_templates/` 
    - [x] CHANGELOG.md

**Comment by xgaia** [comment]
+ ajouter un service postgesql dans le fichiers `docker-compose.yml`

**Comment by xgaia** [comment]
+ modifier le formulaire de selection de source dans le kgcreateor
