### ISSUE TITLE
Bug build SLS-PY-API

### ISSUE THREAD

**Issue by claudefauconnet** [souslesens/souslesensVocables#595]
Claude Fauconnet <claude.fauconnet@gmail.com>
08:35 (il y a 54 minutes)
À Xavier

Building sls-api
Step 1/11 : FROM docker.io/library/python:3.11-alpine
3.11-alpine: Pulling from library/python
661ff4d9561e: Already exists
44cda88cd45d: Pull complete
2cbca0db7eef: Pull complete
5c03c2d36281: Pull complete
f3eb635f7e92: Pull complete
Digest: sha256:b9cc19c4f422bd75cfcbef7b6ea563270629da3fd8652c4f9ec94217ce1a9693
Status: Downloaded newer image for python:3.11-alpine
 ---> d624407390d5
Step 2/11 : RUN apk add --no-cache poetry
 ---> Running in 87b97f783fca
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
(1/91) Installing libgcc (13.2.1_git20231014-r0)
(2/91) Installing libstdc++ (13.2.1_git20231014-r0)
(3/91) Installing mpdecimal (2.5.1-r2)
(4/91) Installing python3 (3.11.6-r1)
(5/91) Installing python3-pycache-pyc0 (3.11.6-r1)
(6/91) Installing pyc (3.11.6-r1)
(7/91) Installing py3-poetry-plugin-export (1.6.0-r0)
(8/91) Installing py3-poetry-plugin-export-pyc (1.6.0-r0)
(9/91) Installing py3-parsing (3.1.1-r0)
(10/91) Installing py3-parsing-pyc (3.1.1-r0)
(11/91) Installing py3-packaging (23.2-r0)
(12/91) Installing py3-packaging-pyc (23.2-r0)
(13/91) Installing py3-pyproject-hooks (1.0.0-r1)
(14/91) Installing py3-pyproject-hooks-pyc (1.0.0-r1)
(15/91) Installing py3-build (1.0.3-r0)
(16/91) Installing py3-build-pyc (1.0.3-r0)
(17/91) Installing py3-msgpack (1.0.7-r0)
(18/91) Installing py3-msgpack-pyc (1.0.7-r0)
(19/91) Installing py3-certifi (2023.7.22-r0)
(20/91) Installing py3-certifi-pyc (2023.7.22-r0)
(21/91) Installing py3-charset-normalizer (3.3.2-r0)
(22/91) Installing py3-charset-normalizer-pyc (3.3.2-r0)
(23/91) Installing py3-idna (3.6-r0)
(24/91) Installing py3-idna-pyc (3.6-r0)
(25/91) Installing py3-urllib3 (1.26.18-r0)
(26/91) Installing py3-urllib3-pyc (1.26.18-r0)
(27/91) Installing py3-requests (2.31.0-r1)
(28/91) Installing py3-requests-pyc (2.31.0-r1)
(29/91) Installing py3-cachecontrol (0.13.1-r0)
(30/91) Installing py3-cachecontrol-pyc (0.13.1-r0)
(31/91) Installing py3-crashtest (0.4.1-r2)
(32/91) Installing py3-crashtest-pyc (0.4.1-r2)
(33/91) Installing py3-rapidfuzz (3.5.2-r0)
(34/91) Installing py3-rapidfuzz-pyc (3.5.2-r0)
(35/91) Installing py3-cleo (2.1.0-r0)
(36/91) Installing py3-cleo-pyc (2.1.0-r0)
(37/91) Installing py3-dulwich (0.21.6-r0)
(38/91) Installing py3-dulwich-pyc (0.21.6-r0)
(39/91) Installing py3-installer (0.7.0-r1)
(40/91) Installing py3-installer-pyc (0.7.0-r1)
(41/91) Installing py3-zipp (3.17.0-r0)
(42/91) Installing py3-zipp-pyc (3.17.0-r0)
(43/91) Installing py3-importlib-metadata (7.0.0-r0)
(44/91) Installing py3-importlib-metadata-pyc (7.0.0-r0)
(45/91) Installing py3-more-itertools (10.1.0-r0)
(46/91) Installing py3-more-itertools-pyc (10.1.0-r0)
(47/91) Installing py3-jaraco.classes (3.3.0-r0)
(48/91) Installing py3-jaraco.classes-pyc (3.3.0-r0)
(49/91) Installing py3-jeepney (0.8.0-r3)
(50/91) Installing py3-jeepney-pyc (0.8.0-r3)
(51/91) Installing py3-cparser (2.21-r4)
(52/91) Installing py3-cparser-pyc (2.21-r4)
(53/91) Installing py3-cffi (1.16.0-r0)
(54/91) Installing py3-cffi-pyc (1.16.0-r0)
(55/91) Installing py3-cryptography (41.0.7-r0)
(56/91) Installing py3-cryptography-pyc (41.0.7-r0)
(57/91) Installing py3-secretstorage (3.3.3-r2)
(58/91) Installing py3-secretstorage-pyc (3.3.3-r2)
(59/91) Installing py3-keyring (24.2.0-r0)
(60/91) Installing py3-keyring-pyc (24.2.0-r0)
(61/91) Installing py3-ptyprocess (0.7.0-r5)
(62/91) Installing py3-ptyprocess-pyc (0.7.0-r5)
(63/91) Installing py3-pexpect (4.9-r0)
(64/91) Installing py3-pexpect-pyc (4.9-r0)
(65/91) Installing py3-pkginfo (1.9.6-r1)
(66/91) Installing py3-pkginfo-pyc (1.9.6-r1)
(67/91) Installing py3-platformdirs (4.0.0-r0)
(68/91) Installing py3-platformdirs-pyc (4.0.0-r0)
(69/91) Installing py3-requests-toolbelt (1.0.0-r0)
(70/91) Installing py3-requests-toolbelt-pyc (1.0.0-r0)
(71/91) Installing py3-shellingham (1.5.4-r0)
(72/91) Installing py3-shellingham-pyc (1.5.4-r0)
(73/91) Installing py3-tomlkit (0.12.3-r0)
(74/91) Installing py3-tomlkit-pyc (0.12.3-r0)
(75/91) Installing py3-trove-classifiers (2023.11.29-r0)
(76/91) Installing py3-trove-classifiers-pyc (2023.11.29-r0)
(77/91) Installing py3-distlib (0.3.7-r2)
(78/91) Installing py3-distlib-pyc (0.3.7-r2)
(79/91) Installing py3-filelock (3.12.4-r0)
(80/91) Installing py3-filelock-pyc (3.12.4-r0)
(81/91) Installing py3-virtualenv (20.24.6-r0)
(82/91) Installing py3-virtualenv-pyc (20.24.6-r0)
(83/91) Installing poetry-pyc (1.7.1-r0)
(84/91) Installing py3-fastjsonschema-pyc (2.19.0-r0)
(85/91) Installing py3-lark-parser (1.1.7-r0)
(86/91) Installing py3-lark-parser-pyc (1.1.7-r0)
(87/91) Installing py3-poetry-core-pyc (1.8.1-r0)
(88/91) Installing python3-pyc (3.11.6-r1)
(89/91) Installing py3-fastjsonschema (2.19.0-r0)
(90/91) Installing py3-poetry-core (1.8.1-r0)
(91/91) Installing poetry (1.7.1-r0)
Executing busybox-1.36.1-r15.trigger
OK: 101 MiB in 129 packages
Removing intermediate container 87b97f783fca
 ---> b23ce0a3b9f8
Step 3/11 : WORKDIR /src
 ---> Running in a2d35469e0e9
Removing intermediate container a2d35469e0e9
 ---> 41624f3be9e4
Step 4/11 : COPY poetry.lock pyproject.toml README.md /src/
 ---> 4cd625893b32
Step 5/11 : RUN poetry install
 ---> Running in 36c77f0e91ff
Creating virtualenv sls-api-VsnhxLU2-py3.11 in /root/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 38 installs, 0 updates, 0 removals

  • Installing idna (3.6)
  • Installing six (1.16.0)
  • Installing sniffio (1.3.0)
  • Installing typing-extensions (4.8.0)
  • Installing annotated-types (0.6.0)
  • Installing anyio (3.7.1)
  • Installing isodate (0.6.1)
  • Installing pydantic-core (2.14.5)
  • Installing pyparsing (3.1.1)
  • Installing certifi (2023.11.17)
  • Installing charset-normalizer (3.3.2)
  • Installing click (8.1.7)
  • Installing h11 (0.14.0)
  • Installing httptools (0.6.1)
  • Installing iniconfig (2.0.0)
  • Installing mypy-extensions (1.0.0)
  • Installing packaging (23.2)
  • Installing pathspec (0.11.2)
  • Installing platformdirs (4.0.0)
  • Installing pluggy (1.3.0)
  • Installing pydantic (2.5.2)
  • Installing python-dotenv (1.0.0)
  • Installing pyyaml (6.0.1)
  • Installing rdflib (7.0.0)
  • Installing starlette (0.27.0)
  • Installing urllib3 (2.1.0)
  • Installing uvloop (0.19.0)
  • Installing watchfiles (0.21.0)
  • Installing websockets (12.0)
  • Installing black (23.11.0)
  • Installing colorlog (6.7.0)
  • Installing pytest (7.4.3)
  • Installing python-multipart (0.0.6)
  • Installing sparqlwrapper (2.0.0)
  • Installing requests (2.31.0)
  • Installing fastapi (0.104.1)
  • Installing python-ulid (2.2.0)
  • Installing uvicorn (0.24.0.post1)

Installing the current project: sls-api (0.2.0)
The current project could not be installed: No file/folder found for package sls-api
If you do not want to install the current project use --no-root

Removing intermediate container 36c77f0e91ff
 ---> 566012a1f624
Step 6/11 : COPY sls_api /src/sls_api
 ---> ff70eda3d7d2
Step 7/11 : RUN poetry install
 ---> Running in 90b1f657f605
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: sls-api (0.2.0)
Removing intermediate container 90b1f657f605
 ---> 8e50dfe9bcf3
Step 8/11 : COPY config.ini.default /src/config.ini
 ---> e6e06372487a
Step 9/11 : EXPOSE 8000
 ---> Running in a16c37c44e0e
Removing intermediate container a16c37c44e0e
 ---> ece4d0094600
Step 10/11 : COPY --chmod=755 entrypoint.sh /entrypoint.sh
ERROR: Service 'sls-api' failed to build: the --chmod option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
root@vps-5ef950f8:/var/lib/sls/souslesensVocables#

**Comment by xgaia** [comment]
Il faut mettre à jour Docker pour utiliser buildKit

https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
