### ISSUE TITLE
ConfigEditor: add a form to edit mainConfig.json entries

### ISSUE THREAD

**Issue by xgaia** [souslesens/souslesensVocables#762]
on doit pouvoir modifier seulement les champs suivants :
- defaultGroups
- tools_available
- theme

**Comment by xgaia** [comment]
branche `origin/feat/configeditor-settings-tab`

**Comment by fbessou** [comment]
Pour le moment, default_groups n'apparait pas dans la réponse de /api/v1/config, est-ce qu'on le rajoute ? Pour tout le monde ou seulement si l'utilisateur courant est administrateur ?

**Comment by xgaia** [comment]
@fbessou on pourrait le rajouter seulement pour les admin oui.

**Comment by xgaia** [comment]
ou faire une route admin_config avec la config admin?
