### ISSUE TITLE
Upload into virtuoso graph of sources.json at startup

### ISSUE THREAD

**Issue by xgaia** [souslesens/souslesensVocables#815]
Charger les graphs par défaut lors de l'installation

Chargement à partir de https://industryportal.enit.fr/ontologies

**Comment by ounnoughikarim** [comment]
Add sources : 
- IDO 
- BFO
- IOF_core
- HR-MODEL-ABOX-REF 
- HRMODEL-IDO-REF

**Comment by xgaia** [comment]
AJouter un champs `downloadUrl` avec l'url de téléchargement du RDF.

Au démarrage, changer les sources qui ne sont pas chargé
